I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 4, in script call
    call chap1 from _call_chap1
  File "game/Chapter1/chap1.rpy", line 73, in script
    play music bg0 fadein 1.0
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/Chapter1/chap1.rpy", line 73, in <module>
    play music bg0 fadein 1.0
NameError: name 'bg0' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 4, in script call
    call chap1 from _call_chap1
  File "game/Chapter1/chap1.rpy", line 73, in script
    play music bg0 fadein 1.0
  File "renpy/ast.py", line 2010, in execute
    self.call("execute")
  File "renpy/ast.py", line 1998, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "renpy/python.py", line 2254, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2247, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Chapter1/chap1.rpy", line 73, in <module>
    play music bg0 fadein 1.0
NameError: name 'bg0' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.7.1862
Forbidden Fruit 0.2.0
Sat Aug 28 10:37:48 2021
